### ISSUE TITLE
插件安装成功，工具栏没有按钮

### ISSUE THREAD

**Issue by DuShuYuan** [zhengcx/MethodTraceMan#1]
android studio 3.5

**Comment by zhengcx** [comment]
安装后需要重启Androidstduio

**Comment by DuShuYuan** [comment]
重启了  还是没有

**Comment by zhengcx** [comment]
提示安装成功了吗?Androidstduio有弹什么error提示吗，或者Androidstduio的helper里搜一下methodtraceman看看

**Comment by DuShuYuan** [comment]
重新安装也不行，提示成功，重启AS，没有错误提示

**Comment by zhengcx** [comment]
没有遇到这种情况，可以加我交流解决下，微信:zcx7hao

**Comment by zhengcx** [comment]
在AndroidStduio顶部栏 View->Toolbar 勾选上即可展示出来了
