### ISSUE TITLE
无法获取方法耗时

### ISSUE THREAD

**Issue by d745282469** [zhengcx/MethodTraceMan#16]
配置文件信息：
#配置需插桩的包,如果为空，则默认所有文件都进行插桩(config the package need to trace,If they are empty, all files are traced by default.)
-tracepackage com/dong/newnovel

#在需插桩的包下设置无需插桩的包(Setting up traceless packages under packages that require trace)
#-keeppackage cn/cxzheng/asmtraceman/test

#在需插桩的包下设置无需插桩的类(Setting up traceless classes under packages that require trace)
#-keepclass cn/cxzheng/asmtraceman/MainActivity

#插桩代码所在类,这里固定配置为：cn/cxzheng/tracemanui/TraceMan(Fixed configuration here: cn/cxzheng/tracemanui/TraceMan)
-beatclass cn/cxzheng/tracemanui/TraceMan#

**Comment by zhengcx** [comment]
是windows系统吗

**Comment by zhengcx** [comment]
是windows系统吗

**Comment by zhengcx** [comment]
> 配置文件信息：
> #配置需插桩的包,如果为空，则默认所有文件都进行插桩(config the package need to trace,If they are empty, all files are traced by default.)
> -tracepackage com/dong/newnovel
> 
> #在需插桩的包下设置无需插桩的包(Setting up traceless packages under packages that require trace)
> #-keeppackage cn/cxzheng/asmtraceman/test
> 
> #在需插桩的包下设置无需插桩的类(Setting up traceless classes under packages that require trace)
> #-keepclass cn/cxzheng/asmtraceman/MainActivity
> 
> #插桩代码所在类,这里固定配置为：cn/cxzheng/tracemanui/TraceMan(Fixed configuration here: cn/cxzheng/tracemanui/TraceMan)
> -beatclass cn/cxzheng/tracemanui/TraceMan#

已解决Window系统上换行符导致的配置文件解析问题，更新tracemanplugin版本号至1.0.4即可，感谢反馈：
dependencies {
classpath "gradle.plugin.cn.cxzheng.methodTracePlugin:tracemanplugin:1.0.4"
}
