### ISSUE TITLE
配置完，没有看到日志，浏览器加载错误

### ISSUE THREAD

**Issue by githulining** [zhengcx/MethodTraceMan#19]
请问下，为什么我参照你文章中说的那样，配置，编译完成后，运行后看不到log，并且打开浏览器，浏览器加载错误？
是哪个环节有问题吗？

#插桩代码所在类,这里固定配置为：cn/cxzheng/tracemanui/TraceMan(Fixed configuration here: cn/cxzheng/tracemanui/TraceMan)
-beatclass cn/cxzheng/tracemanui/TraceMan

这个直接copy就可以了吗，不用修改吗？

**Comment by zhengcx** [comment]
看一下问题排障和注意事项，然后看看自己的操作流程有没有问题，traceConfig放的位置和配置的插桩范围要正确

**Comment by zhengcx** [comment]
浏览器加载错误就表明手机连接错误或者有多台手机连接，建议adb devices看看是否连接成功并且只连一台设备，确保连接成功的情况下，进入app初始化完MethodTraceMan后点击小灯泡，可以成功打开浏览器UI界面
