### ISSUE TITLE
浏览器看不到数据,Log日志只有两条。怎么排查

### ISSUE THREAD

**Issue by ihrthk** [zhengcx/MethodTraceMan#22]
19-11-15 16:53:49.436 13323-13323/pro.huobi I/MethodTraceMan: MethodTraceMan Server is running
2019-11-15 16:53:49.439 13323-13323/pro.huobi I/MethodTraceMan: http://10.154.108.103:5392/index.html

**Comment by ihrthk** [comment]
MethodTraceMan-trace-class 已经插装

**Comment by zhengcx** [comment]
插桩成功吗？操作手机没有方法耗时日志输出？记得MethodTraceServerManager.logLevel = MethodTraceServerManager.MTM_LOG_DETAIL 打开日志输出
