### ISSUE TITLE
已向浏览器发送0条方法耗时信息

### ISSUE THREAD

**Issue by z876335662** [zhengcx/MethodTraceMan#25]
插装应该没错 耗时日志也有 。为啥上传0条

**Comment by zhengcx** [comment]
看一下操作步骤次序是否有按照文档描述，如果耗时日志有看到的话，按理应该不可能上传0条

**Comment by 103style** [comment]
@zhengcx   直接同步最新的源代码   运行也是提示 已向浏览器发送0条方法耗时信息

**Comment by zhengcx** [comment]
> @zhengcx 直接同步最新的源代码 运行也是提示 已向浏览器发送0条方法耗时信息

是Windows系统吗

**Comment by 103style** [comment]
@zhengcx  我的是 windows 10

**Comment by zhengcx** [comment]
window上对插桩配置文件的换行解析可能有点问题，近期我解决一下，欢迎关注

**Comment by zhengcx** [comment]
> @zhengcx 我的是 windows 10

已解决Window系统上换行符导致的配置文件解析问题，更新tracemanplugin版本号至1.0.4即可：
dependencies {
 classpath "gradle.plugin.cn.cxzheng.methodTracePlugin:tracemanplugin:1.0.4"
}
