### ISSUE TITLE
项目build不成功，Gson有冲突

### ISSUE THREAD

**Issue by ljl2014** [zhengcx/MethodTraceMan#27]
我项目导了一个converter-gson-2.3.0.jar包,按你的说明配置好后一build项目后就报错了，你项目中用一了google的gson包吗？怎么解决？出错如下：Duplicate class com.google.gson.DefaultDateTypeAdapter found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.ExclusionStrategy found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.FieldAttributes found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.FieldNamingPolicy found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.FieldNamingPolicy$1 found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.FieldNamingPolicy$2 found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.FieldNamingPolicy$3 found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.FieldNamingPolicy$4 found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.FieldNamingPolicy$5 found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.FieldNamingStrategy found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and gson-2.8.5.jar (gson-2.8.5.jar)
Duplicate class com.google.gson.Gson found in modules gson-2.8.0.jar (com.google.code.gson:gson:2.8.0) and

**Comment by andych008** [comment]
在主工程的`build.gradle`文件中试试
```
compile ('com.squareup.retrofit2:converter-gson:2.3.0'){
	exclude group: 'com.google.code.gson', module: 'gson' 
}
```

**Comment by zhengcx** [comment]
有依赖库的冲突可以自行统一一个版本进行解决，统一依赖库版本的方法可以网上搜索，感谢反馈
