### ISSUE TITLE
无法输出统计结果，显示No data

### ISSUE THREAD

**Issue by iHardWorking** [zhengcx/MethodTraceMan#3]
无法输出统计结果，显示No data

**Comment by iHardWorking** [comment]
![20191028175012](https://user-images.githubusercontent.com/16016184/67668741-7b9b2600-f9ab-11e9-9f11-294bb235d11e.png)

**Comment by zhengcx** [comment]
看一下是否有按步骤操作，并且保证没有同时启动两个集成了methodtraceman的APP,如果还有问题的话，加我vx交流解决，谢谢

**Comment by iHardWorking** [comment]
> 看一下是否有按步骤操作，并且保证没有同时启动两个集成了methodtraceman的APP,如果还有问题的话，加我vx交流解决，谢谢

大佬微信多少？

**Comment by zhengcx** [comment]
zcx7hao

**Comment by iHardWorking** [comment]
已添加，麻烦通过一下






------------------ 原始邮件 ------------------
发件人: "DavidSu"<notifications@github.com>;
发送时间: 2019年10月29日(星期二) 上午9:16
收件人: "zhengcx/MethodTraceMan"<MethodTraceMan@noreply.github.com>;
抄送: "867152290"<867152290@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhengcx/MethodTraceMan] 无法输出统计结果，显示No data (#3)




zcx7hao

**Comment by 543441727** [comment]
我也遇到了  在华为p20pro上   运行的是MethodTraceMan项目

**Comment by TangHaifeng-John** [comment]
我也遇到类似的问题，能否加下微信看看是怎么回事吗？

**Comment by zhengcx** [comment]
看下最新的集成文档，增加了丰富的日志输出配置，来排查到底是哪个环节出现了问题，谢谢
