### ISSUE TITLE
when  the `traceManConfig.open` to `false` ，There is no class in the apk file.

### ISSUE THREAD

**Issue by pdog18** [zhengcx/MethodTraceMan#34]
https://github.com/zhengcx/MethodTraceMan/blob/73bd816b8795758c05593c3afe3f7d4296e3e87c/tracemanplugin/src/main/groovy/cn/cxzheng/tracemanplugin/TraceManTransform.groovy#L52

Empty transform function, can't put the class into the apk file.

**Comment by zhengcx** [comment]
> https://github.com/zhengcx/MethodTraceMan/blob/73bd816b8795758c05593c3afe3f7d4296e3e87c/tracemanplugin/src/main/groovy/cn/cxzheng/tracemanplugin/TraceManTransform.groovy#L52
> 
> Empty transform function, can't put the class into the apk file.

I will fix this soon in next version, thank you for feedback.
