### ISSUE TITLE
1.0.7版本找不到

### ISSUE THREAD

**Issue by guofeng007** [zhengcx/MethodTraceMan#35]
如题

**Comment by guofeng007** [comment]
是不要要先 adb forward tcp:5392 tcp:5392

**Comment by nianzhen** [comment]
同样的问题：Could not resolve com.github.zhengcx:MethodTraceMan:1.0.7

**Comment by zhengcx** [comment]
之前应该是可以更新下来了，估计今天jitpack有问题，我等下看一下

**Comment by zhengcx** [comment]
我试了下1.0.7是可以拉到的，看一下是否按照文档进行集成。1.0.5可以拉到吗？

**Comment by nianzhen** [comment]
> 我试了下1.0.7是可以拉到的，看一下是否按照文档进行集成。1.0.5可以拉到吗？

可以了。
