### ISSUE TITLE
插件不兼容Android studio  4.1.2

### ISSUE THREAD

**Issue by hxy493045049** [zhengcx/MethodTraceMan#48]
如题, 插件不兼容. 
incompatible (support only in IntellJ IDEA)
请问有其他办法查看统计信息吗

**Comment by zhengcx** [comment]
注意：如果升级AndroidStduio4.x后安装此plugin报错提示：Plugin  is incompatible (supported only in IntelliJ IDEA).

解决方案：

1.cd到AndroidStduio安卓目录下的plugins文件夹下，如/Users/xxx/Library/ApplicationSupport/Google/AndroidStudio4.x/plugins

2.删除此文件夹下的methodtraceman-plugin.jar

3.重启AndroidStduio，重新安装此插件即可。

**Comment by ZHB5145** [comment]
您好  我的问题没解决   重新安装这个文件又下回来了
