### ISSUE TITLE
大佬，as的插件有考虑开源不

### ISSUE THREAD

**Issue by willpyshan13** [zhengcx/MethodTraceMan#5]
大佬，as的插件有考虑开源不

**Comment by luckybilly** [comment]
+1

**Comment by luckybilly** [comment]
@willpyshan13 刚用JD-GUI看了一下asplugin/methodtraceman-plugin.jar，AS插件的功能也很简单：

1. 找到当前项目local.properties中配置的sdk.dir
2. 调用命令： sdk.dir/platform-tools/adb forward tcp:%s tcp:%s
3. 打开网页：http://localhost:%s/index.html

adb forward命令的实际应用技能get！

感谢！@zhengcx

**Comment by willpyshan13** [comment]
> @willpyshan13 刚用JD-GUI看了一下asplugin/methodtraceman-plugin.jar，AS插件的功能也很简单：
> 
> 1. 找到当前项目local.properties中配置的sdk.dir
> 2. 调用命令： sdk.dir/platform-tools/adb forward tcp:%s tcp:%s
> 3. 打开网页：http://localhost:%s/index.html
> 
> adb forward命令的实际应用技能get！
> 
> 感谢！@zhengcx

感谢大佬，我研究下

**Comment by SmallBlueWhale** [comment]
> @willpyshan13 刚用JD-GUI看了一下asplugin/methodtraceman-plugin.jar，AS插件的功能也很简单：
> 
> 1. 找到当前项目local.properties中配置的sdk.dir
> 2. 调用命令： sdk.dir/platform-tools/adb forward tcp:%s tcp:%s
> 3. 打开网页：http://localhost:%s/index.html
> 
> adb forward命令的实际应用技能get！
> 
> 感谢！@zhengcx

补充下，这个adb forward作用是是打通pc和mobile，能让他们通过固定端口进行数据传输比如socket
