### ISSUE TITLE
频繁gc,导致卡顿，不监控时希望可以暂停内部操作

### ISSUE THREAD

**Issue by hansionit** [zhengcx/MethodTraceMan#7]
频繁打印
I/zygote: WaitForGcToComplete blocked Alloc on HeapTrim for 21.864ms
I/zygote: Starting a blocking GC Alloc
I/zygote: Starting a blocking GC Alloc
I/zygote: Waiting for a blocking GC Alloc
I/zygote: Waiting for a blocking GC Alloc
I/zygote: Background concurrent copying GC freed 865(288MB) AllocSpace objects, 0(0B) LOS objects, 33% free, 95MB/143MB, paused 293us total 121.579ms
I/zygote: WaitForGcToComplete blocked Alloc on HeapTrim for 76.357ms
I/zygote: Starting a blocking GC Alloc
I/zygote: WaitForGcToComplete blocked Alloc on HeapTrim for 29.824ms
I/zygote: Starting a blocking GC Alloc

频繁GC对检测的结果会造成影响，并且在没有进行检测的时候，希望暂停内部的操作

**Comment by zhengcx** [comment]
你点击结束耗时统计按钮后，就会清空app内存里保存的耗时统计数据的，如果你点击开始耗时统计后，长时间的操作手机，那是有可能由于收集的耗时数据过多，导致GC的。我周末再看下是否有此问题，感谢反馈~

**Comment by hansionit** [comment]
点击了结束也打印的，所以才来反馈的

**Comment by zhengcx** [comment]
好的，周末排查下

**Comment by zhengcx** [comment]
已解决，请更新到1.0.6版本（可以查看最新的集成文档）
