### ISSUE TITLE
http://localhost:5392/index.html 无法访问此网站

### ISSUE THREAD

**Issue by o0o0oo00** [zhengcx/MethodTraceMan#9]
localhost 拒绝了我们的连接请求。
请在 Google 中搜索“localhost 5392 index”
ERR_CONNECTION_REFUSED

请求帮助~

**Comment by 543441727** [comment]
我也是出现了这种问题

**Comment by zhengcx** [comment]
1.确认启动了APP并执行到methodtraceman的初始化方法
2.确认usb连接手机成功，并且不能同时连接两台手机，可以通过adb devices查看是否连接成功并且只连接一台设备

**Comment by 543441727** [comment]
对了 我想问一下   我是开发盒子的，通过adb连接盒子的，盒子上可以使用吗？

**Comment by zhengcx** [comment]
没试过盒子，你可以试一下，按照我说的步骤，只能连接一台设备，然后启动APP，然后再点小灯泡启动浏览器界面

**Comment by 543441727** [comment]
好的  ，谢谢

**Comment by o0o0oo00** [comment]
原来我连接了两个设备，只留下一个就可以打开网页了，谢谢@zhengcx
